# Exercise: Linear algebra operations with NumPy

[NumPy](https://numpy.org/) is the library that gives Python its ability to work with numerical data at speed. This exercise will demonstrate how to use NumPy for common tasks such as the creation and manipulation of arrays, linear algebra operations, and statistical operations. Some of the content is inspired by one (out of many) [cheat sheets](https://github.com/Nothingaholic/python-cheat-sheet) found on [github](https://github.com).

The structure of this note:

1. N-dimensional arrays
1. Array shape manipulations
1. Linear algebra and numerical operations
1. Array manipulations routines ( select and split)
1. Statistical operations

In [1]:
import numpy as np

## N dimensional arrays

### What are arrays?
Arrays are a data structure for storing elements of the same type. Each item stored in an array is called an element. Each location of an element in an array has a numerical index which is used to identify the element. Arrays (and the indices) can be of more than one dimension.

### 1D vs 2D Array
1D array (i.e., single dimensional array) stores a list of variables of the same data type. It is possible to access each variable using the index.

2D array (i.e, multi-dimensional array) stores data in a format consisting of rows and columns. Each index will then be two numbers.

### Arrays vs Lists
- Arrays use less memory than lists
- Arrays have significantly more functionality
- Arrays require data to be homogeneous; lists do not
- Arithmetic on arrays operates like matrix multiplication
- NumPy is used to work with arrays. The array object in NumPy is called `ndarray`.

### Create Arrays

In [2]:
# Create 1 dimensional array (vector)
np.array([1,2,3]) # Create vector as a row

array([1, 2, 3])

In [3]:
np.array([[1],[2],[3]]) #Create vector as a column. This is now a two-dimensional array.

array([[1],
       [2],
       [3]])

In [6]:
np.array([(1,2,3),(4,5,6)]) # Two-dimensional array mith multiple rows and columns.

array([[1, 2, 3],
       [4, 5, 6]])

`````{admonition} Zero-based indexing
:class: tip
Note that elements in `ndarrays` are accessed with zero-based indexing, meaning that the numbering starts with zero.
`````

`````{admonition} Row-major order
:class: tip
Note that elements in `ndarrays` are stored in memory using *row-major order*.

In computing, row-major order and column-major order are methods for storing multidimensional arrays in linear storage such as random access memory.

The difference between the orders lies in which elements of an array are contiguous in memory. In row-major order, the consecutive elements of a row reside next to each other, whereas the same holds true for consecutive elements of a column in column-major order. 

Data layout is critical for correctly passing arrays between programs written in different programming languages. It is also important for performance when traversing an array because modern CPUs process sequential data more efficiently than nonsequential data.
`````

### Creating a Sparse Matrix
A sparse matrix is a matrix in which most of the elements are zero. Sparse matrix data formats only store nonzero elements and assume all other values will be zero, leading to significant computational savings.

Let’ say, we want to create a NumPy array with two nonzero values, then converted it into a sparse matrix. If we view the sparse matrix, we can see that only the nonzero values are stored:

In [5]:
from scipy import sparse
matrix_large = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                         [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
                         [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
# Create compressed sparse row (CSR) matrix
matrix_large_sparse = sparse.csr_matrix(matrix_large)
print(matrix_large_sparse)

  (1, 1)	1
  (2, 0)	3


In the example above, (1, 1) and (2, 0) represent the indices of the non-zero values 1 and 3, respectively. For example, the element 1 is in the second row and second column (remember that numbering starts at zero!).

### Create special `ndarray`

Here are some examples of `numpy` methods that can be used to create special arrays.

In [6]:
# Create  1d array of zeros, length 3
np.zeros(3) 

array([0., 0., 0.])

In [7]:
# 2x3 array of zeros
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
# Create array of ones, 3x4 (3 rows, 4 columns)
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
#  5x5 array of 0 with 1 on diagonal (Identity matrix)
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
# Array of 6 evenly divided values from 0 to 100
np.linspace(0,100,6)

array([  0.,  20.,  40.,  60.,  80., 100.])

In [11]:
# Array of values from 0 to less than 10 with step 3 
np.arange(0,10,3)

array([0, 3, 6, 9])

In [12]:
# 2x3 array with all values 5
np.full((2,3),5)

array([[5, 5, 5],
       [5, 5, 5]])

In [13]:
# 2x3 array of random floats between 0–1
np.random.rand(2,3)

array([[0.44182313, 0.19051442, 0.83397729],
       [0.93012309, 0.33034137, 0.27159291]])

In [14]:
# 2x3 array of random floats between 0–100
np.random.rand(2,3)*100

array([[65.82836754, 31.77520274, 86.3442516 ],
       [28.89289403, 16.22230131, 10.99366733]])

In [15]:
# 2x3 array with random ints between 0–4
np.random.randint(5,size=(2,3))

array([[0, 1, 0],
       [2, 3, 1]])

Remember that useful `shift-Tab-Tab` shortcut in Jupyter notebooks to quickly find the docstring of a function. You can try it on any of the functions shown above.

You can also use the `np.info` function.

In [16]:
np.info(np.eye) # View documentation for np.eye

 eye(N, M=None, k=0, dtype=<class 'float'>, order='C')

Return a 2-D array with ones on the diagonal and zeros elsewhere.

Parameters
----------
N : int
  Number of rows in the output.
M : int, optional
  Number of columns in the output. If None, defaults to `N`.
k : int, optional
  Index of the diagonal: 0 (the default) refers to the main diagonal,
  a positive value refers to an upper diagonal, and a negative value
  to a lower diagonal.
dtype : data-type, optional
  Data-type of the returned array.
order : {'C', 'F'}, optional
    Whether the output should be stored in row-major (C-style) or
    column-major (Fortran-style) order in memory.

    .. versionadded:: 1.14.0

Returns
-------
I : ndarray of shape (N,M)
  An array where all elements are equal to zero, except for the `k`-th
  diagonal, whose values are equal to one.

See Also
--------
identity : (almost) equivalent function
diag : diagonal 2-D array from a 1-D array specified by the user.

Examples
--------
>>> np.eye(2, dt

## Array shape manipulations

### Shape, size, length and data type
It will be valuable to check the shape and size of an array both for further calculations and simply as a sanity check after some operation.

NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

In [32]:
arr = np.array([(1,2,3),(4,5,6)])
arr.shape # Returns dimensions of arr (rows,columns)

(2, 3)

In the example above, (2, 3) means that the array has 2 dimensions, and each dimension has 3 elements.

In [34]:
arr.size # Return number of elements in arr

6

In [35]:
len(arr) # Number of array dimension

2

In [36]:
arr.dtype # Return type of elements in arr

dtype('int64')

In [37]:
arr.dtype.name # Name of data type

'int64'

In [40]:
arr_int = arr.astype(float) # Convert an array to a different type
arr_int.dtype

dtype('float64')

### Reshape
It is important to know how to reshape the NumPy arrays so that our data meets the expectation of specific Python libraries. For example, Scikit- learn requires a one-dimensional array of output variables to be shaped like a two-dimensional array with one column and outcomes for each row.

Other algorithms might require input to be specified as a three-dimensional array. One example is the Long Short-Term Memory recurrent neural network in Keras that expects a three-dimensional input of samples, timesteps, and features.

`np.reshape()` allows us to restructure an array so that we maintain the same data but it is organized as a different number of rows and columns.

Note: The shape of the original and new matrix contains the same number of elements (i.e, same size).

In [188]:
# Reshaping
arr1 = np.arange(1, 11)  # numbers 1 to 10
print(f'arr1 = {arr1}\n')
print(f'The shape of array `arr1` is: {arr1.shape}\n') # Prints a tuple for the one dimension.

arr1_2d = arr1.reshape(2, 5)
print(f'Reshaping the array into:\n{arr1_2d}')
print(f'The shape is now: {arr1_2d.shape}\n')

arr1 = [ 1  2  3  4  5  6  7  8  9 10]

The shape of array `arr1` is: (10,)

Reshaping the array into:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
The shape is now: (2, 5)



The `reshape` method has a useful option of specifying `-1` as one of the shape elements. This will then automatically become the required number to maintain the array size.

In [189]:
arr1.reshape(2, 5)
arr1.reshape(-1, 5)  # same as above: arr1.reshape(2, 5)
arr1.reshape(2, -1)  # same as above: arr1.reshape(2, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

Transposing a matrix (rows <=> columns) or flattening into a one-dimensional array. 

In [239]:
# Transpose
arr1_2d.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [190]:
# Flattening a Matrix
arr1_2d.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Note that the default of flatten is to use the row-major order. Can you find the argument to flatten with column-major instead?

In [54]:
# Resize arr1_2d to 3 rows, 4 columns 
np.resize(arr1_2d, (3,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10,  1,  2]])

### Array to/from List conversion

Arrays need to be declared whereas lists do not need declaration because they are a part of Python’s syntax. This is the reason lists are more often used than arrays. But in case of performing some arithmetic function to our list, we should go with arrays instead.

It is possible to convert between lists and arrays (although list to array conversion requires the object to be of a single type).

In [191]:
arr = np.array([(1,2,3),(4,5,6)])
print(arr)
type(arr)

[[1 2 3]
 [4 5 6]]


numpy.ndarray

In [192]:
arr_to_list = arr.tolist() # Convert arr to a Python list
print(arr_to_list)
type(arr_to_list)

[[1, 2, 3], [4, 5, 6]]


list

In [193]:
arr_from_list = np.array(arr_to_list) # Convert list to array
print(arr_from_list)
type(arr_from_list)

[[1 2 3]
 [4 5 6]]


numpy.ndarray

The following operation will not work with a list, but does work with an array.

In [194]:
arr_to_list/4

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [195]:
arr_from_list/4

array([[0.25, 0.5 , 0.75],
       [1.  , 1.25, 1.5 ]])

## Linear algebra and numerical operations

Let's explore some of the numerical operations that can be performed with matrices. We will often use methods from the [`np.linalg`](https://numpy.org/doc/stable/reference/routines.linalg.html) module. Note that these NumPy linear algebra functions rely on BLAS and LAPACK to provide efficient low level implementations of standard linear algebra algorithms. 

### Trace
The trace is the sum of all the diagonal elements of a square matrix.

In [247]:
arr = np.array([[2, 0, 0], [0, 2, 0], [0, 0, 2]])
np.trace(arr)

6

### Inverse

In [55]:
matrix = np.array([[1, 2],
                   [3, 4]])
# Calculate inverse of matrix
np.linalg.inv(matrix)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

### Determinant

In [249]:
# Determinant
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])
# Return determinant of matrix
np.linalg.det(matrix)

0.0

### Rank

In [58]:
# Rank of a matrix
matrix = np.array([[1, 1, 3],
                   [1, 2, 4],
                   [1, 3, 0]])
# Return matrix rank
np.linalg.matrix_rank(matrix)

3

Question: Why is the rank of the 3x3 matrix below not equal to 3?

In [196]:
# Rank of a matrix
matrix = np.array([[1, 7, 3],
                   [1, 9, 4],
                   [1, 1, 0]])
# Return matrix rank
np.linalg.matrix_rank(matrix)

2

### Eigenvalues and eigenvectors

In [65]:
# Eigenvalues and Eigenvectors
matrix = np.array([[0, 1, 2],
                   [3, 4, 5],
                   [6, 7, 8]])
# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print(f'Eigenvalues: {eigenvalues}')
print(f'Eigenvectors: {eigenvectors}')

Eigenvalues: [ 1.33484692e+01 -1.34846923e+00 -1.26963291e-15]
Eigenvectors: [[ 0.16476382  0.79969966  0.40824829]
 [ 0.50577448  0.10420579 -0.81649658]
 [ 0.84678513 -0.59128809  0.40824829]]


`````{admonition} Operating on matrices with special properties
:class: tip
Note that there are methods that are targeted to work on matrices with certain properties, such as `np.linalg.eigh` for complex Hermitian (conjugate symmetric) or a real symmetric matrix. Be careful, however, as it can produce incorrect results if applied to an object that does not have the required property.
`````

### Scalar operations
When we add, subtract, multiply or divide a matrix by a number, this is called the scalar operation. During scalar operations, the scalar value is applied to each element in the array, therefore, the function returns a new matrix with the same number of rows and columns.

In [69]:
# Scalar Operations
new_arr = np.arange(1,10)

# Add 1 to each array element
np.add(new_arr,1)

np.subtract(arr,2) # Subtract 2 from each array element
np.multiply(arr,3) # Multiply each array element by 3
np.divide(arr,4) # Divide each array element by 4 (returns np.nan for division by zero)
np.power(arr,5) # Raise each array element to the 5th power

array([[   1,   32,  243],
       [1024, 3125, 7776]])

### Matrix  Operations
A matrix can only be added to (or subtracted from) another matrix if the two matrices have the same dimensions, that is, they must have the same number of rows and columns.

When multiplying matrices, we take rows of the first matrix and multiply them by the corresponding columns of the second matrix.

In [90]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.ones_like(arr1)*2
print('arr1 =\n',arr1)
print('arr2 =\n',arr2)

arr1 =
 [[1 2]
 [3 4]]
arr2 =
 [[2 2]
 [2 2]]


In [87]:
print('Elementwise add arr2 to arr1:\n',np.add(arr1,arr2)) 
print('Elementwise subtract arr2 from arr1:\n',np.subtract(arr1,arr2)) 
print('Elementwise multiply arr1 by arr2:\n',np.multiply(arr1,arr2))
print('Elementwise divide arr1 by arr2:\n',np.divide(arr1,arr2))
print('Elementwise raise arr1 to the power of arr2:\n',np.power(arr1,arr2))
print('Return True if the arrays have the same elements and shape:',np.array_equal(arr1,arr2))

Elementwise add arr2 to arr1:
 [[3 4]
 [5 6]]
Elementwise subtract arr2 from arr1:
 [[-1  0]
 [ 1  2]]
Elementwise multiply arr1 by arr2:
 [[2 4]
 [6 8]]
Elementwise divide arr1 by arr2:
 [[0.5 1. ]
 [1.5 2. ]]
Elementwise raise arr1 to the power of arr2:
 [[ 1  4]
 [ 9 16]]
Return True if the arrays have the same elements and shape: False


Other math operations

In [91]:
np.sqrt(arr) # Square root of each element in the array
np.sin(arr) # Sine of each element in the array
np.log(arr) # Natural log of each element in the array
np.abs(arr) # Absolute value of each element in the array
np.ceil(arr) # Rounds up to the nearest int
np.floor(arr) # Rounds down to the nearest int
np.round(arr) # Rounds to the nearest int

array([[1, 2, 3],
       [4, 5, 6]])

### Dot product versus elementwise multiplication

The dot product of two matrices can be computed with the `np.dot` function. Note that it is not the same as the arithmetic `∗`  operation that performs elementwise multiplication (Hadamard product).

In [96]:
A = np.array([[1,2],[3,4]])
print('A =\n',A)
print(r'The dot product A \cdot A:')
AA = np.dot(A,A)
print(AA)
print(r'Element-wise product A * A:')
print(A*A)

A =
 [[1 2]
 [3 4]]
The dot product A \cdot A:
[[ 7 10]
 [15 22]]
Element-wise product A * A:
[[ 1  4]
 [ 9 16]]


The dot product of a matrix by its inverse returns the identity matrix (with small floating point errors). **Verify that this is true.**

`````{admonition} Further examples with numpy
:class: tip
The [NumPy tutorial](https://www.numpy.org/devdocs/user/quickstart.html) is a good resource.
`````

## Array Manipulation Routines

### Adding/removing elements
The `np.append()` function is used to append values to the end of a given array.

In [ ]:
# Adding/removing Elements
np.append ([0, 1, 2], [[3, 4, 5], [6, 7, 8]])
np.append([[0, 1, 2], [3, 4, 5]],[[6, 7, 8]], axis=0)

The axis along which values are appended. If the axis is not given, both array and values are flattened before use.

`np.insert()'` is used to insert the element before the given index of the array.

In [99]:
np.insert(arr,2,10) # Inserts 10 into arr before index 2

array([ 1,  2, 10,  3,  4,  5,  6])

While `np.delete()` can be used to delete any row and column from the `ndarray`.

In [101]:
arr = np.arange(12).reshape(3, 4)
print('arr =\n',arr)
np.delete(arr,2,axis=0) # Deletes row (axis=0) on index 2 of arr
np.delete(arr,3,axis=1) # Deletes column (axis=1) on index 3 of arr

arr =
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10]])

### Sorting
The `np.sort()` function can be used to sort the list in both ascending and descending order.

In [108]:
# Sort
oned_arr = np.array([3,8,5,1])
np.sort(oned_arr)
arr = np.array([[5, 4, 6, 8],
                [1, 2, 4, 8],
                [1, 5, 2, 4]])
# sort each column of arr
np.sort(arr, axis=0)

# sort each row of X
np.sort(arr, axis=1)

array([[4, 5, 6, 8],
       [1, 2, 4, 8],
       [1, 2, 4, 5]])

### Concatenate arrays

Concatenating means putting contents of two or more arrays in a single array. In NumPy, we join arrays by axes. We pass a sequence of arrays that we want to join to the `np.concatenate()` function, along with the axis. If the axis is not explicitly passed, it is taken as 0.

In [104]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
# Adds arr2 as rows to the end of arr1
np.concatenate((arr1, arr2), axis=0)

array([1, 2, 3, 4, 5, 6])

In [106]:
arr1 = np.array([[1, 2, 3],[4, 5, 6]])
arr2 = np.array([[7, 8, 9],[10, 11, 12]])
# Adds arr2 as columns to end of arr1
np.concatenate((arr1,arr2),axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

### Splitting arrays

We use `np.array_split()` for splitting arrays. We pass it the array we want to split and the number of splits.

In [111]:
# Splitting NumPy Arrays
# Splits arr into 4 sub-arrays
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 4) 
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


or `np.hsplit()` to split horizontally.

In [112]:
arr = np.array([1, 2, 3, 4, 5, 6])
# Splits arr horizontally on the 2nd index
newarr = np.hsplit(arr, 2)
print(newarr)

[array([1, 2, 3]), array([4, 5, 6])]


### Select element(s)
NumPy offers a wide variety of methods for selecting and slicing elements or groups of elements in arrays.

In [120]:
user_name = np.array(['Katie','Bob','Scott','Liz','Sam'])
articles = np.array([100, 38, 91, 7, 25])

In [121]:
user_name[4] # Returns the element at index 4

'Sam'

In [122]:
articles[3] = 17 # Assigns array element on index 1 the value 4

In [123]:
user_name[0:3] # Returns the elements at indices 0,1,2

array(['Katie', 'Bob', 'Scott'], dtype='<U5')

In [124]:
user_name[:2] # Returns the elements at indices 0,1

array(['Katie', 'Bob'], dtype='<U5')

In [125]:
articles<50 # Returns an array with boolean values

array([False,  True, False,  True,  True])

In [126]:
articles[articles < 50] # Returns the element values

array([38, 17, 25])

In [127]:
# Returns the user_name that read more than 50 articles but less than 100 articles
user_name[(articles < 100 ) & (articles >50)]

array(['Scott'], dtype='<U5')

In [135]:
# Multi-dimensinal arrays
arr = np.arange(36).reshape(6,6)
print(arr)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


Exercise: **Try to perform the following selection or assignments of elements**:
* Returns the 2D array element on index [2][5]
* Assigns array element on index [1][3] the value 10
* Returns rows 0,1,2
* Returns the elements on rows 0,1,2 at column 4
* Returns returns rows 0,1
* Returns the elements at index 1 on all rows
* Returns all elements that are divisible by 3.

Solutions are found below

In [145]:
arr[2,5] # Returns the 2D array element on index [2][5]

17

In [146]:
arr[1,3]=10 # Assigns array element on index [1][3] the value 10
print(arr)

[[ 0  1  2  3  4  5]
 [ 6  7  8 10 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [147]:
arr[0:3] # Returns rows 0,1,2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8, 10, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [148]:
arr[0:3,4] # Returns the elements on rows 0,1,2 at column 4

array([ 4, 10, 16])

In [149]:
arr[:2] # Returns returns rows 0,1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8, 10, 10, 11]])

In [150]:
arr[:,1] # Returns the elements at index 1 on all rows

array([ 1,  7, 13, 19, 25, 31])

In [151]:
arr[np.mod(arr,3)==0] # returns all elements that are divisible by 3.

array([ 0,  3,  6, 12, 15, 18, 21, 24, 27, 30, 33])

## Statistical Operations

### Find the Maximum and Minimum Values
Often we want to know the maximum and minimum value in an array or subset of an array. This can be accomplished with the `np.max` and `np.min` methods. Using the axis parameter we can also apply the operation along a certain axis.

In [153]:
articles = np.array([[10, 23, 17],
                   [41, 54, 65],
                   [71, 18, 89]])
# Return maximum element
np.max(articles)

89

In [154]:
np.max(articles, axis=0) # Find maximum element in each column

array([71, 54, 89])

In [156]:
np.max(articles, axis=1) # Find maximum element in each row

array([23, 65, 89])

### Average, Variance, and Standard Deviation
We can easily get descriptive statistics about the whole matrix or do calculations along a single axis.

In [168]:
# 4x6 array of random floats between 0–100
arr=np.random.rand(4,6)*100
print(arr)

[[51.61411251 98.63727273 78.51299733 47.67397746 38.13394163 79.94982351]
 [20.79711846 28.45940689 15.43565341 65.56489745 62.2039607  82.87812458]
 [63.63362561 33.48293456 93.26403931 32.75818936 82.11566672 60.11872442]
 [13.36831461 89.02273101 70.53427644 82.72384089  1.75790964  0.77140016]]


In [172]:
np.mean(arr) # Returns the mean of all elements

53.89220580775009

In [173]:
arr.sum() # Returns the sum of all elements

1293.412939386002

In [174]:
np.mean(arr,axis=0) # Returns the mean along a specific axis

array([37.3532928 , 62.4005863 , 64.43674162, 57.18022629, 46.05286967,
       55.92951817])

In [175]:
arr.cumsum(axis=1) #Cumulative sum of the elements

array([[ 51.61411251, 150.25138524, 228.76438257, 276.43836003,
        314.57230166, 394.52212517],
       [ 20.79711846,  49.25652534,  64.69217876, 130.25707621,
        192.4610369 , 275.33916148],
       [ 63.63362561,  97.11656017, 190.38059948, 223.13878884,
        305.25445556, 365.37317998],
       [ 13.36831461, 102.39104562, 172.92532207, 255.64916296,
        257.4070726 , 258.17847276]])

In [177]:
np.var(arr) # Returns the variance

863.0809445721999

In [178]:
np.std(arr,axis=1) # Returns the standard deviation along specific axis

array([21.35148044, 25.43722262, 22.54357085, 38.33277061])

In [179]:
np.corrcoef(arr) # Returns correlation coefficient of array

array([[ 1.        , -0.27255049, -0.2131374 ,  0.42867177],
       [-0.27255049,  1.        , -0.23623217, -0.40174745],
       [-0.2131374 , -0.23623217,  1.        , -0.46511119],
       [ 0.42867177, -0.40174745, -0.46511119,  1.        ]])